name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # مینوئل بٹن دبانے کے لیے

jobs:
  build:
    runs-on: ubuntu-latest
    
    # یہ لائن بتاتی ہے کہ اصل پروجیکٹ کس فولڈر میں ہے
    defaults:
      run:
        working-directory: ./PrayerTimeApp

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Dependencies
      run: npm install

    - name: Add Android Platform
      run: npx cap add android

    - name: Generate App Icons
      run: npx @capacitor/assets generate --android

    - name: Sync Web Files
      run: npx cap sync android

    - name: Build APK
      working-directory: ./PrayerTimeApp/android
      run: ./gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        # تیار شدہ APK ڈاؤنلوڈ کرنے کے لیے درست پاتھ
        path: PrayerTimeApp/android/app/build/outputs/apk/debug/app-debug.apk
